---
- hosts: workstation

  tasks:
    - name: install intellij idea 15 community
      mac_pkg: pkg_type=app
               url=https://download.jetbrains.com/idea/ideaIC-15.0.3-custom-jdk-bundled.dmg
               archive_type=dmg archive_path='IntelliJ IDEA 15 Community Edition.app'
      sudo: yes
